### ISSUE TITLE
this looks cool but question

### ISSUE THREAD

**Issue by ORESoftware** [opentable/spur-ioc#11]
My question is, you have an example on the main Readme page, but the example doesn't seem to show how to inject dependencies that might be captured asynchronously.

For example, you may be aware of the --delay flag in Mocha. Mocha has this flag so that it waits for a certain amount of time before running, so that asynchronous dependencies can be loaded, but the problem is you have to guess how long to wait!

Like so:

``` js
setTimeout(function(){

     describe('aTest', function(){

       });

   run();  // the --delay flag adds run as a global which will run your test after the 5 second delay (very bad)

}, 5000);
```

This is a perfect use case for DI/IoC - Mocha should allow you to specify a dependency array like so

``` js
describe('aTest', ['A','B','C'], function(A,B,C){


});
```

where A B and C are secured asynchronously, and are only injected once they are ready (fire a callback or ready event, etc).

I am writing a successor to Mocha -  Can I use this library for something like this?

by the way, as an aside, TMK if your code is never going to be minified, then you don't need the dependency array of strings, you can just do this

``` js
describe('aTest', function(A,B,C){


});
```

as long as A, B, C match exactly what you want

**Comment by ssetem** [comment]
Hi :), we only support synchronous dependencies atm.

Have you got more details on your usecase? it might be you need to synchronously inject a provider which then does async with use of promises etc

**Comment by ORESoftware** [comment]
thanks, I mentioned the use case above, it's for replacing Mocha's --delay option with an IoC container

**Comment by ORESoftware** [comment]
It is my belief that DI/IoC is much more useful in Node if it procures dependencies that are loaded asynchronously. Do you describe the use case for this library somewhere?

**Comment by ssetem** [comment]
we never had a strong enough usecase to load application source dependencies asynchronously as it introduces alot of complexity. loading non executional async dependencies was usually a concern of the application in our case.

**Comment by acolchado** [comment]
@ORESoftware As mentioned above, we purposely wanted the make the initialization of the injector be synchronous so that we could determine at app start up the state of ready. 

In some cases we have things like:

``` javascript
injector().inject(function(WebServer, DiscoveryClient){
  WebServer.start().then(function(){
     // Server is started, ready to announce to discovery
     DiscoveryClient.start()
  })
})
```

With an async model, we could not have a clear understanding of ready. In order to do that, we would have to introduce a level of complexity that we didn't see a clear use and benefit for. We will review and take in feedback over time and determine if something needs to change at that point.
