### ISSUE TITLE
DI for ES6 classes

### ISSUE THREAD

**Issue by wishabhilash** [opentable/spur-ioc#16]
Can spur in its current form be used in ES6 classes??? Like...
`class A{
    constructor(b, c){}
}`

where b and c are the dependencies.

**Comment by acolchado** [comment]
@wishabhilash Yes, it should. We are currently working on switching over to ES6, but the example of how to do it is probably a few days away. Sorry for the delay, didn't get the alert for his issue.

**Comment by acolchado** [comment]
Closing this because we are evaluating different approaches for the second gen of this package. 

We will also evaluate this request as part of that.
